Insert into EXCHANGE_VALUE (ID,CONVERSION_MULTIPLE,CURRENCY_FROM,PORT,CURRENCY_TO) values (1000,65,'USD',0,'INR');
Insert into EXCHANGE_VALUE (ID,CONVERSION_MULTIPLE,CURRENCY_FROM,PORT,CURRENCY_TO) values (1001,100,'EU',0,'EU');
Insert into EXCHANGE_VALUE (ID,CONVERSION_MULTIPLE,CURRENCY_FROM,PORT,CURRENCY_TO) values (1002,45,'AUD',0,'INR');
Insert into EXCHANGE_VALUE (ID,CONVERSION_MULTIPLE,CURRENCY_FROM,PORT,CURRENCY_TO) values (1003,50,'YEN',0,'INR');